group: bluezone
language: node_js
sudo: true
cache:
  directories:
  - node_modules
node_js: stable
branches:
  only:
  - dev
  - master
deploy:
  - provider: cloudfoundry
    api: https://api.w3ibm.bluemix.net
    username: $CF_USER
    password: $CF_PASSWORD
    organization: ciomobiledev
    space: dev
    manifest: manifest.dev.yml
    name: ask-mobile-ibm
    on:
        repo: MobileAtIBM/ask-mobileatibm
        branch: dev
  - provider: cloudfoundry
    api: https://api.w3ibm.bluemix.net
    username: $CF_USER
    password: $CF_PASSWORD
    organization: ciomobiledev
    space: prod
    manifest: manifest.prod.yml
    name: ask-mobileatibm
    on:
        repo: MobileAtIBM/ask-mobileatibm
        branch: master
