language: node_js
sudo: true
cache:
  directories:
  - node_modules
node_js: stable
branches:
  only:
  - dev
  - master
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: anacecih@mx1.ibm.com
  password: Acha9895
  organization: CIO-mobile@ibm
  space: dev
  manifest: manifest.dev.yml
  name: ask-mobile-ibm
  on:
    repo: MobileAtIBM/ask-mobileatibm
    branch: dev
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: anacecih@mx1.ibm.com
  password: Acha9895
  organization: CIO-mobile@ibm
  space: Prod
  manifest: manifest.prod.yml
  name: ask-mobileatibm
  on:
    repo: MobileAtIBM/ask-mobileatibm
    branch: master
